ci(github-actions): ensure always check format validation outcome
Modify the GitHub Actions workflow for Spring Java Format validation tocheck the outcome of the format validation step regardless of the job
status. This change ensures that the format validation result is checked
every time, enforcing code formatting consistency.

diff --git a/.github/workflows/spring-javaformat-validate.yml b/.github/workflows/spring-javaformat-validate.yml
--- a/.github/workflows/spring-javaformat-validate.yml
+++ b/.github/workflows/spring-javaformat-validate.yml
@@ -24,13 +24,17 @@ jobs:
           cache: maven
 
       - name: Execute Spring Java Format Validation
+        id: format-validation
         run: |
           echo "Executing Spring code format validation"
           mvn spring-javaformat:validate
         continue-on-error: true
 
       - name: Check format validation result
-        if: failure()
+        if: always()
         run: |
-          echo "Spring code format validation failed, please run `spring-javaformat:apply` to fix and resubmit"
-          exit 1
+          echo "Checking format validation result"
+          if [ ${{ steps.format-validation.outcome }} == 'failure' ]; then
+            echo "Spring code format validation failed, please run `spring-javaformat:apply` to fix and resubmit"
+            exit 1
+          fi
